### ISSUE TITLE
URL_MD5 information

### ISSUE THREAD

**Issue by SiyuanHuang95** [ethz-asl/opencv3_catkin#30]
Hi,

First, thx for your sharing.

I am trying to use this repo as one template and implement for a new version OpenCv4.2.0, however, I have no idea about the URL_MD5, which seems like a hash about the source.

Can anybody give me some hints about that?

**Comment by mmattamala** [comment]
Hi,

Don't know if you fixed this issue, but if you comment/delete the URL_MD5 requirement it will still work.

Cheers

**Comment by SiyuanHuang95** [comment]
> Hi,
> 
> Don't know if you fixed this issue, but if you comment/delete the URL_MD5 requirement it will still work.
> 
> Cheers

Thanks for your reply.

You are true, I have also fixed that problem with deleting that line which has almost no negative influence about.

Anyway thanks for your information.
